name: github pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TARGET_PATH: CubeWorld/Web
      CACHE_VERSION: v1
      VUE_APP_PHOTON_APP_ID: ${{ secrets.PHOTON_APP_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: ${{ env.TARGET_PATH }}/node_modules
          key: ${{ env.CACHE_VERSION }}-${{ runner.os }}-v12-${{ hashFiles(format('{0}/package-lock.json', env.TARGET_PATH)) }}
          restore-keys: |
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-v12-
      - name: Install
        run: |
          cd ${{ env.TARGET_PATH }}
          npm install
      - name: Build
        run: |
          cd ${{ env.TARGET_PATH }}
          npm run build
          cp dist/index.html dist/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.TARGET_PATH }}/dist
